// <auto-generated />
namespace LexiconUniversity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StudentPhoneNumbers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentPhoneNumbers));
        
        string IMigrationMetadata.Id
        {
            get { return "201806051124250_Student.PhoneNumbers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
